[project]
name = 'Plant-Parent-Failure-Documentation-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.plant-identification-app-usage-vs-mortality-rate]
path = 'contracts/plant-identification-app-usage-vs-mortality-rate.clar'
clarity_version = 3
epoch = '3.2'

[contracts.watering-schedule-good-intentions-tracker]
path = 'contracts/watering-schedule-good-intentions-tracker.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
